### PR TITLE
fastblock lists

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
Adds fastblock lists to stage.ini

### CODE REVIEW

**Comment by ckolos** [comment]
Entries without an s3_key will be cheerfully ignored.

**Comment by fmarier** [comment]
@ckolos  Do the s3_keys have to start with "tracking/" or could we name them "fastblock/..." ?

**Comment by fmarier** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1474412

**Comment by lesleyjanenorton** [comment]
Just made updates to stage with the fastblock s3_keys starting with "tracking/" and "entity/". If they need to begin with "fastblock/" instead, will the whitelists also be starting with "fastblock/"?

**Comment by ckolos** [comment]
the ```s3_key``` is loosely analogous to <dir>/<filename>.

It's been a while since we did this, so I don't know if the <dir> portion needs to exist prior to running the list creation script or not. I suspect that it does, but for stage, we can try letting it run as is and see what happens.

**Comment by fmarier** [comment]
Ok, so maybe we should try using `fastblock/` then?

**Comment by fmarier** [comment]
>  will the whitelists also be starting with "fastblock/"?

I'd personally put them both in the same `fastblock/` directory just to make it clear that they're related to that feature.

**Comment by ckolos** [comment]
wfm

**Comment by lesleyjanenorton** [comment]
Not sure if there was a verdict on the keys, but there they are with s3_key='fastblock/output'. I'll be at my desk the rest of the afternoon and able to make any changes quickly if necessary.

**Comment by groovecoder** [comment]
@ckolos has shavar stage server restarted since this was merged?

**Pull request merged**
